import Providers from "./providers";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/app-sidebar"
import Auth from "@/views/auth/Auth";
// import Navbar from "@/components/ui/navbar";
// import Footer from "@/components/ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`} suppressHydrationWarning>
      <body className="h-full">
        <Providers>
          <SidebarProvider className="h-svh overflow-hidden">
            {/* <Navbar /> */}
              <AppSidebar />
              <main className="relative flex flex-1 flex-col min-h-0">
                {children}
                <SidebarTrigger className="absolute top-2 left-2 z-10" />
              </main>
              <Auth />
            {/* <Footer /> */}
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
