export const API = {
  auth: {
    login: { method: "POST", url: "/api/v1/auth/login" },
    register: { method: "POST", url: "/api/v1/auth/register" },
    logout: { method: "POST", url: "/api/v1/auth/logout" },
    me: { method: "GET", url: "/api/v1/auth/me" },
  },
  idea: {
    add: { method: "POST", url: "/api/v1/ideas" },
    gallery: { method: "GET", url: "/api/v1/ideas" },
    draft: { method: "POST", url: "/api/v1/ideas/draft" },
    byToken: { method: "GET", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}` },
    mine: { method: "GET", url: "/api/v1/me/ideas" },
    update: { method: "PUT", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}` },
    similar: { method: "GET", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/similar` },
    visualize: { method: "POST", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/visualize` },
    visualization: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/visualization`,
    saveCanvas: { method: "PUT", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/canvas` },
    suggestCanvas: { method: "POST", url: (token, step) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/canvas/suggest${step ? `?step=${encodeURIComponent(step)}` : ""}` },
    feedback: { method: "POST", url: (token) => `/api/v1/ideas/by-token/${encodeURIComponent(token)}/feedback` },
  },
  testing: {
    participate: { method: "POST", url: (id) => `/api/v1/testing/${encodeURIComponent(id)}/participation` },
    reviews: { method: "GET", url: (id) => `/api/v1/testing/${encodeURIComponent(id)}/reviews` },
    addReview: { method: "POST", url: (id) => `/api/v1/testing/${encodeURIComponent(id)}/reviews` },
    mine: { method: "GET", url: "/api/v1/me/test-participations" },
    adminList: { method: "GET", url: "/api/v1/admin/testing/participations" },
    adminStatus: { method: "PATCH", url: (id) => `/api/v1/admin/testing/participations/${id}/status` },
  },
  conversation: {
    list: { method: "GET", url: "/api/v1/conversations" },
    create: { method: "POST", url: "/api/v1/conversations" },
    messages: { method: "GET", url: (id) => `/api/v1/conversations/${id}/messages` },
    reply: { method: "POST", url: (id) => `/api/v1/conversations/${id}/messages` },
    status: { method: "PATCH", url: (id) => `/api/v1/conversations/${id}/status` },
  },
  partnership: {
    list: { method: "GET", url: "/api/v1/partnerships" },
    create: { method: "POST", url: "/api/v1/partnerships" },
  },
  config: {
    canvas: { method: "GET", url: "/api/v1/config/canvas" },
    regions: { method: "GET", url: "/api/v1/config/regions" },
  },
  knowledge: {
    resources: { method: "GET", url: "/api/v1/knowledge/resources" },
  },
  grantCall: {
    active: { method: "GET", url: "/api/v1/grant-calls/active" },
    application: { method: "POST", url: (id) => `/api/v1/grant-calls/${id}/application` },
    adminList: { method: "GET", url: "/api/v1/admin/grant-calls" },
    adminCreate: { method: "POST", url: "/api/v1/admin/grant-calls" },
    adminUpdate: { method: "PUT", url: (id) => `/api/v1/admin/grant-calls/${id}` },
    adminDelete: { method: "DELETE", url: (id) => `/api/v1/admin/grant-calls/${id}` },
  },
  adminIdea: {
    list: { method: "GET", url: "/api/v1/admin/ideas" },
    get: { method: "GET", url: (id) => `/api/v1/admin/ideas/${id}` },
    review: { method: "PATCH", url: (id) => `/api/v1/admin/ideas/${id}/review` },
    unseen: { method: "GET", url: "/api/v1/admin/ideas/unseen-count" },
    visualization: (id) => `/api/v1/admin/ideas/${id}/visualization`,
  },
  adminProblem: {
    list: { method: "GET", url: "/api/v1/admin/problems" },
    get: { method: "GET", url: (id) => `/api/v1/admin/problems/${id}` },
    review: { method: "PATCH", url: (id) => `/api/v1/admin/problems/${id}/review` },
    unseen: { method: "GET", url: "/api/v1/admin/problems/unseen-count" },
  },
  adminCatalog: {
    create: { method: "POST", url: "/api/v1/admin/catalog/innovations" },
    update: { method: "PUT", url: (id) => `/api/v1/admin/catalog/innovations/${encodeURIComponent(id)}` },
    remove: { method: "DELETE", url: (id) => `/api/v1/admin/catalog/innovations/${encodeURIComponent(id)}` },
    createResource: { method: "POST", url: "/api/v1/admin/knowledge/resources" },
    updateResource: { method: "PUT", url: (id) => `/api/v1/admin/knowledge/resources/${id}` },
    removeResource: { method: "DELETE", url: (id) => `/api/v1/admin/knowledge/resources/${id}` },
  },
  stats: {
    get: { method: "GET", url: "/api/v1/admin/stats" },
    insights: { method: "POST", url: "/api/v1/admin/stats/insights" },
  },
  middleman: {
    plan: { method: "POST", url: "/api/v1/middleman/plan" },
  },
  catalog: {
    list: { method: "GET", url: "/api/v1/knowledge/innovations" },
    get: { method: "GET", url: (id) => `/api/v1/knowledge/innovations/${encodeURIComponent(id)}` },
    regions: { method: "GET", url: "/api/v1/config/regions" },
  },
  problem: {
    add: { method: "POST", url: "/api/v1/problems" },
    byToken: { method: "GET", url: (token) => `/api/v1/problems/by-token/${encodeURIComponent(token)}` },
    mine: { method: "GET", url: "/api/v1/me/problems" },
    get: { method: "GET", url: "/api/v1/problems/get-problems" },
    reported: { method: "GET", url: "/api/v1/problems/reported" },
    reportedWaiting: { method: "GET", url: "/api/v1/problems/reported/waiting-count" },
    decide: { method: "POST", url: (id) => `/api/v1/problems/reported/${id}/decision` },
    getById: { method: "GET", url: (id) => `/api/v1/problems/${id}` }
  },
};
