spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/app
spring.datasource.username=app
spring.datasource.password=app

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.base-path=/api/actuator
management.endpoint.health.show-details=always

openai.api-key=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
openai.model=gpt-4o-mini